name: Init Project (Copier)

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "App name"
        required: true
        default: "my-service"
      module_path:
        description: "Go module path (e.g., github.com/you/my-service)"
        required: true
      http_port:
        description: "HTTP port"
        required: true
        default: "1010"
      use_postgres:
        type: choice
        options: [true, false]
        default: true
        description: "Include Postgres?"
      use_redis:
        type: choice
        options: [true, false]
        default: false
        description: "Include Redis?"
      use_kafka:
        type: choice
        options: [true, false]
        default: true
        description: "Include Kafka?"

jobs:
  scaffold:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout template repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install copier
        run: pip install copier==9.*

      # Copier خروجی را در پوشه gen/ می‌سازد
      - name: Generate project with Copier
        run: |
          set -euo pipefail
          mkdir -p gen
          copier -f -w \
            -d app_name="${{ inputs.app_name }}" \
            -d module_path="${{ inputs.module_path }}" \
            -d http_port="${{ inputs.http_port }}" \
            -d use_postgres=${{ inputs.use_postgres }} \
            -d use_redis=${{ inputs.use_redis }} \
            -d use_kafka=${{ inputs.use_kafka }} \
            . gen

      # جایگزینی محتوای فعلی با gen/
      - name: Replace repo content with generated files
        run: |
          shopt -s dotglob
          rm -rf !(gen|.git|.github) || true
          mv gen/* ./ || true
          rm -rf gen

      - name: Commit generated scaffold
        run: |
          git config user.name "init-bot"
          git config user.email "init@users.noreply.github.com"
          git add -A
          git commit -m "scaffold: generated with Copier"
          git push
